variable "region" {}
variable "environment" {}
variable "domain" {}
variable "hosted_zone_id" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "instance_types" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "max_unavailable" {}
variable "vpc_cidr" {}
variable "private_subnet_1" {}
variable "private_subnet_2" {}
variable "private_subnet_3" {}
variable "public_subnet_1" {}
variable "public_subnet_2" {}
variable "public_subnet_3" {}
variable "external_dns" {}
variable "alb_ingress" {}
variable "alb_ingress_image_tag" {}